[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
startCommand = "./vertigo-logger"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environment]
DATABASE_URL = "/app/data/vertigo.db"
RUST_LOG = "info"
PORT = "$PORT"

[[environment.volumes]]
mountPath = "/app/data"
name = "vertigo_data"